/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2018-02-28 17:06:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class questionnaireInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/view/footer.jsp", Long.valueOf(1519360719206L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link\n");
      out.write("\thref=\"http://netdna.bootstrapcdn.com/bootstrap/2.3.2/css/bootstrap.min.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("<style type=\"text/css\">\n");
      out.write("form \n");
      out.write("{\n");
      out.write("\ttext-align:center;\n");
      out.write("}\n");
      out.write(" </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<!--설문지 정보.jsp -->\n");
      out.write("\t<!--1. onClick을 자바스크립트로 변경하기 -->\n");
      out.write("\t<form action=\"transmit\" method=\"post\">\n");
      out.write("\t\t<strong>설문지 조사</strong><br /> \n");
      out.write("\t\t1.파손된 물건이 있습니까? &nbsp; 예\n");
      out.write("\t\t\t<input type=\"radio\" name=\"q1\" onClick=\"question1.disabled=false\"> \n");
      out.write("\t\t\t아니오<input type=\"radio\" name=\"q1\" onClick=\"question1.disabled=true\"><br />\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"question1\" style=\"width: 500px; height: 20px;\"><br />\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t2.문을 제대로 닫고 갔습니까?\n");
      out.write("\t\t&nbsp; 예\n");
      out.write("\t\t\t<input type=\"radio\" name=\"q2\" onClick=\"question2.disabled=true\">\n");
      out.write("\t\t\t 아니오<input type=\"radio\" name=\"q2\" onClick=\"question2.disabled=false\"><br />\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"question2\" style=\"width: 500px; height: 20px;\"><br />\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t3.물건을 제자리에 놓았습니까?\n");
      out.write("\t\t&nbsp; 예\n");
      out.write("\t\t\t<input type=\"radio\" name=\"q3\" onClick=\"question3.disabled=true\"> \n");
      out.write("\t\t\t아니오<input type=\"radio\" name=\"q3\" onClick=\"question3.disabled=false\"><br />\n");
      out.write("\t\t\t\t\t <input type=\"text\" name=\"question3\" style=\"width: 500px; height: 20px;\"><br />\n");
      out.write("\t\t\t\t\t \n");
      out.write("\t\t4.의자,책상 등 잘 정리하고 갔습니까? &nbsp; 예\n");
      out.write("\t\t\t<input type=\"radio\" name=\"q4\" onClick=\"question4.disabled=true\"> \n");
      out.write("\t\t\t아니오<input type=\"radio\" name=\"q4\" onClick=\"question4.disabled=false\"><br /> \n");
      out.write("\t\t\t\t<input type=\"text\" name=\"question4\" style=\"width: 500px; height: 20px;\"><br />\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t5.온,냉방시설을 제대로 끄고 갔습니까? &nbsp; 예\n");
      out.write("\t\t<input type=\"radio\" name=\"q5\" onClick=\"question5.disabled=true\"> \n");
      out.write("\t\t\t아니오<input type=\"radio\" name=\"q5\" onClick=\"question5.disabled=false\"><br /> \n");
      out.write("\t\t\t<input type=\"text\" name=\"question5\" style=\"width: 500px; height: 20px;\"><br />\n");
      out.write("\t\t<br /> <input type=\"submit\" class=\"btn btn-primary\" value=\"전송\">\n");
      out.write("\t</form>\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<style>\n");
      out.write(" #aaa\n");
      out.write(" {\n");
      out.write("position:fixed;\n");
      out.write("left:0px;\n");
      out.write("bottom:0px;\n");
      out.write("width: 100%;\n");
      out.write("text-align: center;\n");
      out.write(" }\n");
      out.write(" .inner\n");
      out.write(" {\n");
      out.write(" color: white;\n");
      out.write("width: 400px;\n");
      out.write("padding: 15px;\n");
      out.write("display: inline-block;\n");
      out.write(" }\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<!-- 밑에 이용약관.jsp -->\n");
      out.write("<div id=\"aaa\">\n");
      out.write("\t<div class=\"inner\"\n");
      out.write("\t\tstyle=\"margin-top: 50px; border-top: 1px solid #ddd; padding: 30px; font-size: 10pt; color: #888;\">\n");
      out.write("\t\t<div style=\"float: left; padding-right: 20px;\">\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div>152-716 서울시 구로구 연동로 320 / 지하철 1, 7호선 온수(성공회대입구)역\n");
      out.write("\t\t\tT.02-2610-4114</div>\n");
      out.write("\t\t<div style=\"margin-top: 5px;\">Copyright (c) Sung-Kong-Hoe\n");
      out.write("\t\t\tUnivisity. All rights reserved.</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
